config/routes.rb
Rails.application.routes.draw do
  resources :tools
  root 'tools#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tool.rb
class Tool < ApplicationRecord
	#monetize :price, as: :price_dollars
	def grade
		if grade_low == grade_high
			grade_low&.zero? ? 'K' : grade_low
		else
			"#{grade_low&.zero? ? 'K' : grade_low}-#{grade_high}"
		end
	end

	#def full_price
	#	# noinspection Style/RedundantSelf
	#	"$#{# noinspection RubyResolve
	#	self.price_dollars}"
	#end

	def self.filter(params)
		result = self.all
		%i[	creativity communication collaboration citizenship
				critical_thinking empowered_learner digital_citizen
				knowledge_constructor innovative_designer computational_thinker
				creative_communicator global_collaborator].each do |p|
			result = result.where p => true if params[p]
		end
		if params[:enable_grade_level_filtering]
			result = result.where('grade_low >= :a AND grade_low <= :b OR grade_high >= :a AND grade_high <= :b',
														{a: params[:grade_low], b: params[:grade_high]})
		end
		return result
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
	before_action :set_tool, only: [:show, :edit, :update, :destroy]
	http_basic_authenticate_with name: "techtraining", password: "issaquah2001", only: [:delete, :create, :update, :edit, :new]

	# GET /tools
	# GET /tools.json
	# noinspection RailsChecklist01
	def index
		@tools    = params[:filters] ? Tool.filter(params) : Tool.all
		@pictures = !params[:compact]
	end

	# GET /tools/1
	# GET /tools/1.json
	def show
	end

	# GET /tools/new
	def new
		@tool = Tool.new
	end

	# GET /tools/1/edit
	def edit
	end

	# POST /tools
	# POST /tools.json
	def create
		@tool = Tool.new(tool_params)
		respond_to do |format|
			if @tool.save
				format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
				format.json { render :show, status: :created, location: @tool }
			else
				format.html { render :new }
				format.json { render json: @tool.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /tools/1
	# PATCH/PUT /tools/1.json
	def update
		respond_to do |format|
			if @tool.update(tool_params)
				format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
				format.json { render :show, status: :ok, location: @tool }
			else
				format.html { render :edit }
				format.json { render json: @tool.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /tools/1
	# DELETE /tools/1.json
	def destroy
		@tool.destroy
		respond_to do |format|
			format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_tool
		@tool = Tool.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def tool_params
		params.require(:tool).permit(:name, :description, :picture_url, :platform, :grade_low, :grade_high, :creativity, :communication, :collaboration, :citizenship, :critical_thinking, :empowered_learner, :digital_citizen, :knowledge_constructor, :innovative_designer, :computational_thinker, :creative_communicator, :global_collaborator)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def easy_checkbox(n, l = nil)
		"#{check_box_tag n, true, params[n]}#{label_tag n, (l ? l : n.to_s.humanize)}".html_safe
	end
	def icon(title, attribute, icon_name)
		"<i class=\"material-icons \" style=\"color:#{attribute ? '#2196F3' : 'lightgrey'}\">#{icon_name}</i>".html_safe
	end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/application/_banner.slim
.banner.blue
	.col.s10.offset-s1.blue
		img.banner-img.inline-d src='/EdTech.png' alt='EdTech Logo'
		span.banner-text.white-text TOOL BOX

app/views/layouts/application.slim
doctype html
html
	head
		title = yield :title
		= csrf_meta_tags
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
	meta name="viewport" content="width=device-width, initial-scale=1"

	body
		header.page-header
			- if ['/', '/tools'].include? request.env['PATH_INFO']
				.row
					= render partial: 'banner'
			- else
				.row
					.col.s10.offset-s1
						.section
							h2 = yield :title
						.divider
		main
			.row
				.col.s10.offset-s1 = yield
	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/tools/_card.slim
.card style='width:100%'
	- if tool.picture_url != '' && @pictures
		.card-image
			img src=tool.picture_url
			span.card-title.strokeme = tool.name
	- else
		.card-content
			span.card-title = tool.name
	.card-content
		.row
			.col.s12 = tool.description
		.row
			.col.s12
				div
					= icon 'Creativity', tool.creativity, 'lightbulb_outline'
					= icon 'Communication', tool.communication, 'chat'
					= icon 'Collaboration', tool.collaboration, 'group_work'
					= icon 'Citizenship', tool.citizenship, 'account_balance'
					= icon 'Critical thinking', tool.critical_thinking, 'error'
				div
					= icon 'Empowered learner', tool.empowered_learner, 'power'
					= icon 'Digital citizen', tool.digital_citizen, 'cloud'
					= icon 'Knowledge constructor', tool.knowledge_constructor, 'extension'
					= icon 'Innovative designer', tool.innovative_designer, 'photo'
					= icon 'Computational thinker', tool.computational_thinker, 'pie_chart_outlined'
					= icon 'Creative communicator', tool.creative_communicator, 'create'
					= icon 'Global collaborator', tool.global_collaborator, 'language'
		.row
			/.col.s6
				strong Price
			.col.s6
				strong Grades
		.row
			/.col.s6 = '$' + tool.price_dollars.to_s
			.col.s6 = tool.grade
	.card-action
		= link_to '<i class="material-icons">pageview</i>'.html_safe, tool
		= link_to '<i class="material-icons">edit</i>'.html_safe, edit_tool_path(tool)
		= link_to '<i class="material-icons">delete_forever</i>'.html_safe, tool, data: { confirm: 'Are you sure?' }, method: :delete

app/views/tools/_cards.slim
.row
	.col.s12.cards-container
		- @tools.each do |tool|
			= render partial: 'card', locals: {tool: tool}
br

= link_to 'New Tool', new_tool_path

app/views/tools/_checkbox.slim
= check_box_tag n, true, params[n]
= label_tag n, n.to_s.humanize

app/views/tools/_filters.slim
.row
	ul.collapsible data-collapsible="expandable"
		= render partial: 'filters_21c'
		= render partial: 'filters_iste'
		= render partial: 'filters_grades'

app/views/tools/_filters_21c.slim
li
	.collapsible-header 21st Century Skills
	.collapsible-body
		.row
			.col.s12.m4.l2 = easy_checkbox :creativity
			.col.s12.m4.l2 = easy_checkbox :communication
			.col.s12.m4.l2 = easy_checkbox :collaboration
			.col.s12.m4.l2 = easy_checkbox :citizenship
			.col.s12.m4.l2 = easy_checkbox :critical_thinking

app/views/tools/_filters_iste.slim
li
	.collapsible-header ISTE standards
	.collapsible-body
		.row
			.col.s12.m4.l2 = easy_checkbox :empowered_learner
			.col.s12.m4.l2 = easy_checkbox :digital_citizen
			.col.s12.m4.l2 = easy_checkbox :knowledge_constructor
			.col.s12.m4.l2 = easy_checkbox :innovative_designer
			.col.s12.m4.l2 = easy_checkbox :computational_thinker
			.col.s12.m4.l2 = easy_checkbox :creative_communicator
			.col.s12.m4.l2 = easy_checkbox :global_collaborator

app/views/tools/_form.html.slim
= form_for @tool do |f|
	- if @tool.errors.any?
		#error_explanation
			h2 = "#{pluralize(@tool.errors.count, 'error')} prohibited this tool from being saved:"
			ul
				- @tool.errors.full_messages.each do |message|
					li = message

	.field.input-field
		= f.text_field :name
		= f.label :name
	.field.input-field
		= f.text_area :description, class: 'materialize-textarea'
		= f.label :description
	.field.input-field
		= f.text_field :picture_url
		= f.label :picture_url
	.field.input-field
		= f.text_field :platform
		= f.label :platform
	/.field
		| $
		.input-field.inline
			= f.number_field :price, step: 0.01, min: 0.01
			= f.label :price
	.row
		ul.collapsible data-collapsible="expandable"
			li
				.collapsible-header Grade Level
				.collapsible-body
					.row
						.col.s12.l6
							p.range-field
								= f.label :grade_low, 'From grade'
								= f.range_field :grade_low, min: 0, max: 12, step: 1
						.col.s12.l6
							p.range-field
								= f.label :grade_high, 'To grade'
								= f.range_field :grade_high, min: 0, max: 12, step: 1
			li
				.collapsible-header 21st Century Skills
				.collapsible-body
					.row
						.col.s12.m4.l2
							= f.check_box :creativity
							= f.label :creativity
						.col.s12.m4.l2
							= f.check_box :communication
							= f.label :communication
						.col.s12.m4.l2
							= f.check_box :collaboration
							= f.label :collaboration
						.col.s12.m4.l2
							= f.check_box :citizenship
							= f.label :citizenship
						.col.s12.m4.l2
							= f.check_box :critical_thinking
							= f.label :critical_thinking
			li
				.collapsible-header ISTE standards
				.collapsible-body
					.row
						.col.s12.m4.l2
							= f.check_box :empowered_learner
							= f.label :empowered_learner
						.col.s12.m4.l2
							= f.check_box :digital_citizen
							= f.label :digital_citizen
						.col.s12.m4.l2
							= f.check_box :knowledge_constructor
							= f.label :knowledge_constructor
						.col.s12.m4.l2
							= f.check_box :innovative_designer
							= f.label :innovative_designer
						.col.s12.m4.l2
							= f.check_box :computational_thinker
							= f.label :computational_thinker
						.col.s12.m4.l2
							= f.check_box :creative_communicator
							= f.label :creative_communicator
						.col.s12.m4.l2
							= f.check_box :global_collaborator
							= f.label :global_collaborator
	.actions = f.submit

app/views/tools/_options.slim
= form_tag '/', method: 'get'
	.row
		.col.s12.m4.l3.vmiddle = easy_checkbox :filters
		.col.s12.m4.l3.vmiddle = easy_checkbox :cards, 'Card View'
		.col.s12.m4.l3.vmiddle = easy_checkbox :compact
		.col.s12.l3.right-align
			input.waves-effect.waves-light.btn.blue type='submit'
	- if params[:filters]
		= render partial: 'filters'

app/views/tools/_table.slim
table.responsive-table.highlight
	thead
		tr
			th Name
			th Description
			- if @pictures
				th Picture
			th Platform
			/th Price
			th Grades
			th width="500px" Standards
			th title="View"
				i.material-icons pageview
			th title="Edit"
				i.material-icons edit
			th title="Delete"
				i.material-icons delete_forever

	tbody
		- @tools.each do |tool|
			tr
				td = tool.name
				td = tool.description
				- if @pictures
					td
						img src=tool.picture_url width="100px"
				td = tool.platform
				/td = "$" + tool.price_dollars.to_s
				td = tool.grade
				td
					= icon 'Creativity', tool.creativity, 'lightbulb_outline'
					= icon 'Communication', tool.communication, 'chat'
					= icon 'Collaboration', tool.collaboration, 'group_work'
					= icon 'Citizenship', tool.citizenship, 'account_balance'
					= icon 'Critical thinking', tool.critical_thinking, 'error'

					= icon 'Empowered learner', tool.empowered_learner, 'power'
					= icon 'Digital citizen', tool.digital_citizen, 'cloud'
					= icon 'Knowledge constructor', tool.knowledge_constructor, 'extension'
					= icon 'Innovative designer', tool.innovative_designer, 'photo'
					= icon 'Computational thinker', tool.computational_thinker, 'pie_chart_outlined'
					= icon 'Creative communicator', tool.creative_communicator, 'create'
					= icon 'Global collaborator', tool.global_collaborator, 'language'
				td
					i.material-icons = link_to 'pageview', tool
				td
					i.material-icons = link_to 'edit', edit_tool_path(tool)
				td
					i.material-icons = link_to 'delete_forever', tool, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tool', new_tool_path

app/views/tools/cards.slim
- content_for :title, "Listing tools"

javascript:
  window.onload = function () {
    $('.cards').masonry({
      itemSelector: '.card',
    });
  }

.row
  - @tools.each do |tool|
    .col.s12.m6.l3
      .cards
        .card
          - if tool.picture_url != "" && @pictures
            .card-image
              img src=tool.picture_url
              span.card-title.strokeme = tool.name
          - else
            .card-content
              span.card-title = tool.name
          .card-content
            .row
              .col.s12 = tool.description
            div
              i.material-icons title="Creativity" style="color: #{tool.creativity ? 'black' : 'grey'}" lightbulb_outline
              i.material-icons title="Communication" style="color: #{tool.communication ? 'black' : 'grey'}" chat
              i.material-icons title="Collaboration" style="color: #{tool.collaboration ? 'black' : 'grey'}" group_work
              i.material-icons title="Citizenship" style="color: #{tool.citizenship ? 'black' : 'grey'}" account_balance
              i.material-icons title="Critical thinking" style="color: #{tool.critical_thinking ? 'black' : 'grey'}" error
            div
              i.material-icons title="Empowered learner" style="color: #{tool.empowered_learner ? 'black' : 'grey'}" power
              i.material-icons title="Digital citizen" style="color: #{tool.digital_citizen ? 'black' : 'grey'}" cloud
              i.material-icons title="Knowledge constructor" style="color: #{tool.knowledge_constructor ? 'black' : 'grey'}" extension
              i.material-icons title="Innovative designer" style="color: #{tool.innovative_designer ? 'black' : 'grey'}" photo
              i.material-icons title="Computational thinker" style="color: #{tool.computational_thinker ? 'black' : 'grey'}" pie_chart_outlined
              i.material-icons title="Creative communicator" style="color: #{tool.creative_communicator ? 'black' : 'grey'}" create
              i.material-icons title="Global collaborator" style="color: #{tool.global_collaborator ? 'black' : 'grey'}" language
            .row
              .col.s6
                strong Price
              .col.s6
                strong Grades
            .row
              .col.s6 = '$' + tool.price_dollars.to_s
              .col.s6 = (tool.grade_low == tool.grade_high) ? ((tool.grade_low == 0) ? 'K' : tool.grade_low) : "#{(tool.grade_low == 0) ? 'K' : tool.grade_low}-#{tool.grade_high}"
          .card-action
            = link_to '<i class="material-icons">pageview</i>'.html_safe, tool
            = link_to '<i class="material-icons">edit</i>'.html_safe, edit_tool_path(tool)
            = link_to '<i class="material-icons">delete_forever</i>'.html_safe, tool, data: { confirm: 'Are you sure?' }, method: :delete



/table
  thead
    tr
      th Name
      th Description
      - if @pictures
        th Picture
      th Platform
      th Price
      th Grades
      th title="Creativity"
        i.material-icons lightbulb_outline
      th title="Communication"
        i.material-icons chat
      th title="Collaboration"
        i.material-icons group_work
      th title="Citizenship"
        i.material-icons account_balance
      th title="Critical thinking"
        i.material-icons error
      th title="Empowered learner"
        i.material-icons power
      th title="Digital citizen"
        i.material-icons cloud
      th title="Knowledge constructor"
        i.material-icons extension
      th title="Innovative designer"
        i.material-icons photo
      th title="Computational thinker"
        i.material-icons pie_chart_outlined
      th title="Creative communicator"
        i.material-icons create
      th title="Global collaborator"
        i.material-icons language
      th title="View"
        i.material-icons pageview
      th title="Edit"
        i.material-icons edit
      th title="Delete"
        i.material-icons delete_forever

  tbody
    - @tools.each do |tool|
      tr
        td = tool.name
        td = tool.description
        - if @pictures
          td
            img src=tool.picture_url width="100px"
        td = tool.platform
        td = "$" + tool.price_dollars.to_s
        td = (tool.grade_low == tool.grade_high) ? ((tool.grade_low == 0) ? 'K' : tool.grade_low) : "#{(tool.grade_low == 0) ? 'K' : tool.grade_low}-#{tool.grade_high}"
        td
          i.material-icons = tool.creativity ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.communication ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.collaboration ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.citizenship ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.critical_thinking ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.empowered_learner ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.digital_citizen ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.knowledge_constructor ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.innovative_designer ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.computational_thinker ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.creative_communicator ? "check_circle" : "not_interested"
        td
          i.material-icons = tool.global_collaborator ? "check_circle" : "not_interested"
        td
          i.material-icons = link_to 'pageview', tool
        td
          i.material-icons = link_to 'edit', edit_tool_path(tool)
        td
          i.material-icons = link_to 'delete_forever', tool, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tool', new_tool_path

app/views/tools/edit.html.slim
- content_for :title, "Editing #{@tool.name}"

== render 'form'

= link_to 'Show', @tool
'  |
= link_to 'Back', tools_path

app/views/tools/index.html.slim
- content_for :title, 'EdTech Toolbox'

= render partial: 'options'

- if params[:cards]
	= render partial: 'cards'
- else
	= render partial: 'table'

app/views/tools/new.html.slim
= content_for :title, 'New tool'

== render 'form'

= link_to 'Back', tools_path

app/views/tools/show.html.slim
- content_for :title, @tool.name

.row
	- if @tool.picture_url
		.col.s12.m4.push-m8
			img src=@tool.picture_url width="100%" style="width:100%"
	.col.s12.m8.pull-m4
		p#notice = notice
		blockquote = @tool.description
		p
			strong Platform:&nbsp;
			= @tool.platform
		/p
			strong Price:
			= @tool.price
		p
			strong Grade low:
			= @tool.grade_low
		p
			strong Grade high:
			= @tool.grade_high
		p
			strong Creativity:
			= @tool.creativity
		p
			strong Communication:
			= @tool.communication
		p
			strong Collaboration:
			= @tool.collaboration
		p
			strong Citizenship:
			= @tool.citizenship
		p
			strong Critical thinking:
			= @tool.critical_thinking
		p
			strong Empowered learner:
			= @tool.empowered_learner
		p
			strong Digital citizen:
			= @tool.digital_citizen
		p
			strong Knowledge constructor:
			= @tool.knowledge_constructor
		p
			strong Innovative designer:
			= @tool.innovative_designer
		p
			strong Computational thinker:
			= @tool.computational_thinker
		p
			strong Creative communicator:
			= @tool.creative_communicator
		p
			strong Global collaborator:
			= @tool.global_collaborator

= link_to 'Edit', edit_tool_path(@tool)
'  |
= link_to 'Back', tools_path